version: "3"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - letsencrypt:/etc/letsencrypt
      - ./html:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password
    volumes:
      - mysql_data:/var/lib/mysql

  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/var/www/html --email info@tsutawaru.org --agree-tos --no-eff-email -d tutawaru.org -d www.tutawaru.org
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./html:/var/www/html

volumes:
  mysql_data:
  letsencrypt:
